/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.QuanLyDangNhap;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class FrameDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form FrameDangNhap
     */
    QuanLyDangNhap qlDangNhap;
    
    public FrameDangNhap() {
        initComponents();
        setTitle("PHẦN MỀM QUẢN LÝ BÁN HÀNG");
        setLocationRelativeTo(null);
        setResizable(false);
        qlDangNhap = new QuanLyDangNhap();
    }
    private void checkLogin(){
        String username = usernameFeild.getText().trim();
        String password = passwordFeild.getText();
        if (username.length() == 0 || password.length() == 0) {
            JOptionPane.showMessageDialog(null, "Hãy Điền Đầy Đủ Thông Tin ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else if (qlDangNhap.Login(username, password) == 0) {
            qlDangNhap.login(0, "");
//            this.hide();
        } else if (qlDangNhap.Login(username, password) == 1) {
            qlDangNhap.login(1, username);
            this.hide();
        } else {
            JOptionPane.showMessageDialog(null, "Sai Tên Đăng Nhập Hoặc Mật Khẩu", "Thông Báo", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginMsgFeild = new javax.swing.JLabel();
        passwordFeild = new javax.swing.JPasswordField();
        usernameFeild = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 690));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1270, 670));

        loginMsgFeild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginMsgFeild.setForeground(new java.awt.Color(255, 0, 0));
        loginMsgFeild.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginMsgFeild.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginMsgFeild.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(loginMsgFeild);
        loginMsgFeild.setBounds(760, 200, 470, 30);

        passwordFeild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordFeild.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.add(passwordFeild);
        passwordFeild.setBounds(840, 350, 320, 30);

        usernameFeild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameFeild.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usernameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFeildActionPerformed(evt);
            }
        });
        jLayeredPane1.add(usernameFeild);
        usernameFeild.setBounds(840, 280, 320, 30);

        loginButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\letha\\Desktop\\images.jpg")); // NOI18N
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setHideActionText(true);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(loginButton);
        loginButton.setBounds(890, 430, 180, 40);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\letha\\Desktop\\Project.jpg")); // NOI18N
        Background.setMinimumSize(new java.awt.Dimension(1, 1));
        jLayeredPane1.add(Background);
        Background.setBounds(0, 0, 1270, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFeildActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        checkLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginMsgFeild;
    private javax.swing.JPasswordField passwordFeild;
    private javax.swing.JTextField usernameFeild;
    // End of variables declaration//GEN-END:variables
}
