/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import controller.QuanLyBanHang;
import controller.QuanLyDangNhap;
import controller.QuanLyNhanVien;
import controller.QuanLySanPham;
//import controller.QuanLyThuChi;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.NhanVien;
import model.SanPham;

/**
 *
 * @author tungb_000
 */
public class FrameNhanVien extends javax.swing.JFrame {

    QuanLySanPham qlSanPham;
    QuanLyNhanVien qlNhanVien;
    QuanLyBanHang qlBanHang;
    QuanLyDangNhap qlDangNhap;
//    QuanLyThuChi qlThuChi;
    ArrayList<NhanVien> ds_NhanVien;
    ArrayList<HoaDon> ds_HoaDon;
    private ArrayList<SanPham> ds_SanPham;
    String user;
    NhanVien nv;
    

    /**
     * Creates new form FrameNhanVien
     */
    public FrameNhanVien(String user) {
        this.user = user;
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("PHẦN MỀM QUẢN LÝ BÁN HÀNG");
        reset();
//        qlThuChi = new QuanLyThuChi();
        qlDangNhap = new QuanLyDangNhap();
        tfTongTien.setEditable(false);
        qlBanHang = new QuanLyBanHang();
        ds_HoaDon = qlBanHang.getDsHoaDon();
        lbNgayThangNam.setText(getDate(lbNgayThangNam));
        qlNhanVien = new QuanLyNhanVien();
        ds_NhanVien = qlNhanVien.getDS_NhanVien();
        for (int i = 0; i < ds_NhanVien.size(); i++) {
            if (ds_NhanVien.get(i).getTenDangNhap().equals(user)) {
                lbchao.setText(ds_NhanVien.get(i).getTenNhanVien());
                nv = ds_NhanVien.get(i);
                break;
            }
        }
        qlSanPham = new QuanLySanPham(tableSanPham);
        qlSanPham.load_SanPham();
        ds_SanPham = qlSanPham.getDS_SanPham();
//        ds_DiaNhac = qlSanPham.getDS_DiaNhac();
//        ds_DiaPhim = qlSanPham.getDS_DiaPhim();
//        ArrayList ds = qlSanPham.thongKe();
//        showThongKeSP(ds);
    }

//    public static void showThongKeSP(ArrayList ds) {
//        lbSoLuongSP.setText("Tổng Số Lượng Sản Phẩm: " + ds.get(0));
//        tfSoSach.setText(ds.get(1) + "");
//        tfSoSach.setEditable(false);
//        tfSoDiaNhac.setText(ds.get(3) + "");
//        tfSoDiaNhac.setEditable(false);
//        tfSoDiaPhim.setText(ds.get(2) + "");
//        tfSoDiaPhim.setEditable(false);
//        tfTongGiaTri.setText(ds.get(4) + "");
//        tfTongGiaTri.setEditable(false);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblMaSanPham2 = new javax.swing.JLabel();
        lblNhaCungCap2 = new javax.swing.JLabel();
        lblTenSanPham2 = new javax.swing.JLabel();
        lblGiaMua2 = new javax.swing.JLabel();
        lblGiaBan2 = new javax.swing.JLabel();
        tfTenSanPham = new javax.swing.JTextField();
        tfMaSanPham = new javax.swing.JTextField();
        tfThuongHieu = new javax.swing.JTextField();
        btCapNhatSanPham = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        tfGiaMua = new javax.swing.JTextField();
        tfGiaBan = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btThemSanPham = new javax.swing.JButton();
        btXoaSanPham = new javax.swing.JButton();
        lbthem3 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        lblDonVi = new javax.swing.JLabel();
        tfDonVi = new javax.swing.JTextField();
        lblLoaiSanPham = new javax.swing.JLabel();
        tfLoaiSanPham = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pnKhachHang6 = new javax.swing.JPanel();
        pnChiTietBanHang7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableBanHang = new javax.swing.JTable();
        tfTongTien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnXacNhan7 = new javax.swing.JButton();
        pnThongTinSPBanHang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tenKhachHangField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfThemSoLuong = new javax.swing.JTextField();
        btThemVaoGioHang = new javax.swing.JButton();
        btXoakhoigiohang = new javax.swing.JButton();
        soDienThoaiField = new javax.swing.JTextField();
        tfThemMaSanPham = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbchao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbNgayThangNam = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        DangXuat = new javax.swing.JMenuItem();
        Thoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÝ BÁN HÀNG");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(0, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        lblMaSanPham2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaSanPham2.setText("Mã Sản Phẩm");

        lblNhaCungCap2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhaCungCap2.setText("Thương Hiệu");

        lblTenSanPham2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenSanPham2.setText("Tên Sản Phẩm");

        lblGiaMua2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGiaMua2.setText("Vốn :");

        lblGiaBan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGiaBan2.setText("Giá Bán:");

        tfTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenSanPhamActionPerformed(evt);
            }
        });

        tfMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaSanPhamActionPerformed(evt);
            }
        });

        btCapNhatSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCapNhatSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/repair.png"))); // NOI18N
        btCapNhatSanPham.setText("Cập Nhật");
        btCapNhatSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatSanPhamActionPerformed(evt);
            }
        });

        btThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btThoat.setText(" Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 102));
        jLabel46.setText("VND");

        jLabel47.setBackground(new java.awt.Color(0, 102, 102));
        jLabel47.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 102, 102));
        jLabel47.setText("VND");

        btThemSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addproduct.png"))); // NOI18N
        btThemSanPham.setText("Thêm Mới");
        btThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemSanPhamActionPerformed(evt);
            }
        });

        btXoaSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/removeproduct.png"))); // NOI18N
        btXoaSanPham.setText("Xóa");
        btXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaSanPhamActionPerformed(evt);
            }
        });

        lbthem3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbthem3.setText("Số Lượng");

        lblDonVi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonVi.setText("Đơn Vị");

        lblLoaiSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoaiSanPham.setText("Loại Sản Phẩm");

        tfLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoaiSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(lblLoaiSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbthem3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblTenSanPham2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblMaSanPham2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lblNhaCungCap2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfTenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGiaMua2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGiaBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btThemSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(tfDonVi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btCapNhatSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(tfLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel15Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblMaSanPham2, lblNhaCungCap2, lblTenSanPham2, lbthem3});

        jPanel15Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfMaSanPham, tfSoLuong, tfTenSanPham, tfThuongHieu});

        jPanel15Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblGiaBan2, lblGiaMua2});

        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGiaMua2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfMaSanPham))
                    .addComponent(tfGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGiaBan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfGiaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNhaCungCap2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCapNhatSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbthem3)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );

        jPanel15Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblMaSanPham2, lblNhaCungCap2, lblTenSanPham2, lbthem3});

        jPanel15Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfSoLuong, tfThuongHieu});

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Loại SP", "Đơn Vị", "Vốn", "Giá Bán", "Số Lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableSanPham);
        if (tableSanPham.getColumnModel().getColumnCount() > 0) {
            tableSanPham.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableSanPham.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableSanPham.getColumnModel().getColumn(2).setPreferredWidth(70);
            tableSanPham.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jScrollPane3.setViewportView(jScrollPane5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản Phẩm", new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-cart.png")), jPanel2); // NOI18N

        pnChiTietBanHang7.setBackground(new java.awt.Color(0, 204, 204));
        pnChiTietBanHang7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Giỏ Hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        tableBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Đơn Vị", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tableBanHang);
        if (tableBanHang.getColumnModel().getColumnCount() > 0) {
            tableBanHang.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableBanHang.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableBanHang.getColumnModel().getColumn(2).setHeaderValue("Loại SP");
        }

        tfTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTongTienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setText("TỔNG");

        btnXacNhan7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXacNhan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ok.png"))); // NOI18N
        btnXacNhan7.setText("Thanh Toán");
        btnXacNhan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhan7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChiTietBanHang7Layout = new javax.swing.GroupLayout(pnChiTietBanHang7);
        pnChiTietBanHang7.setLayout(pnChiTietBanHang7Layout);
        pnChiTietBanHang7Layout.setHorizontalGroup(
            pnChiTietBanHang7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietBanHang7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnChiTietBanHang7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChiTietBanHang7Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnXacNhan7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChiTietBanHang7Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        pnChiTietBanHang7Layout.setVerticalGroup(
            pnChiTietBanHang7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietBanHang7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnChiTietBanHang7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pnThongTinSPBanHang.setBackground(new java.awt.Color(0, 204, 204));
        pnThongTinSPBanHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setText("NHẬP MÃ SẢN PHẨM");

        tenKhachHangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenKhachHangFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setText("SỐ LƯỢNG");

        tfThemSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThemSoLuongActionPerformed(evt);
            }
        });

        btThemVaoGioHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btThemVaoGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addproduct.png"))); // NOI18N
        btThemVaoGioHang.setText("Thêm vào giỏ hàng");
        btThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemVaoGioHangActionPerformed(evt);
            }
        });

        btXoakhoigiohang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btXoakhoigiohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addproduct.png"))); // NOI18N
        btXoakhoigiohang.setText("Xóa khỏi giỏ hàng");
        btXoakhoigiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoakhoigiohangActionPerformed(evt);
            }
        });

        soDienThoaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soDienThoaiFieldActionPerformed(evt);
            }
        });

        tfThemMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThemMaSanPhamActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("Tên Khách Hàng");

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("Số Điện Thoại");

        javax.swing.GroupLayout pnThongTinSPBanHangLayout = new javax.swing.GroupLayout(pnThongTinSPBanHang);
        pnThongTinSPBanHang.setLayout(pnThongTinSPBanHangLayout);
        pnThongTinSPBanHangLayout.setHorizontalGroup(
            pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinSPBanHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenKhachHangField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(soDienThoaiField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThongTinSPBanHangLayout.createSequentialGroup()
                        .addComponent(btThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(btXoakhoigiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(pnThongTinSPBanHangLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfThemMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfThemSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        pnThongTinSPBanHangLayout.setVerticalGroup(
            pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinSPBanHangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenKhachHangField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfThemSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfThemMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnThongTinSPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoakhoigiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnThongTinSPBanHangLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5});

        pnThongTinSPBanHangLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tenKhachHangField, tfThemSoLuong});

        javax.swing.GroupLayout pnKhachHang6Layout = new javax.swing.GroupLayout(pnKhachHang6);
        pnKhachHang6.setLayout(pnKhachHang6Layout);
        pnKhachHang6Layout.setHorizontalGroup(
            pnKhachHang6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHang6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKhachHang6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChiTietBanHang7, javax.swing.GroupLayout.PREFERRED_SIZE, 896, Short.MAX_VALUE)
                    .addComponent(pnThongTinSPBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnKhachHang6Layout.setVerticalGroup(
            pnKhachHang6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhachHang6Layout.createSequentialGroup()
                .addComponent(pnThongTinSPBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnChiTietBanHang7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnKhachHang6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnKhachHang6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bán Hàng", new javax.swing.ImageIcon(getClass().getResource("/icon/money.png")), jPanel1); // NOI18N

        lbchao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbchao.setForeground(new java.awt.Color(102, 102, 0));
        lbchao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbchao.setText("Tên nhân Viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setText("Xin Chào :");

        lbNgayThangNam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNgayThangNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNgayThangNam.setText("Thứ ..... Ngày ..... Tháng ..... Năm .....");

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));

        jMenu1.setText("Tùy Chọn");

        DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        DangXuat.setText("Đăng Xuất");
        DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(DangXuat);

        Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        Thoat.setText("Thoát");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });
        jMenu1.add(Thoat);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbchao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNgayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbchao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(lbNgayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thoát", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            qlSanPham.writeSanPhamToFile();
            qlNhanVien.writeNhanVienToFile();
            //qlBanHang.writeHoaDonToFile();
//            qlThuChi.writeThuChiToFile();
            System.exit(0);
        }
    }//GEN-LAST:event_btThoatActionPerformed

    private void btThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemSanPhamActionPerformed
        qlSanPham.themSanPham();
        reset();
    }//GEN-LAST:event_btThemSanPhamActionPerformed

    private void btCapNhatSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatSanPhamActionPerformed
        reset();
        int i = tableSanPham.getSelectedRow();
        try {
            qlSanPham.suaThongTin(i);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btCapNhatSanPhamActionPerformed

    private void btXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaSanPhamActionPerformed
        int i = tableSanPham.getSelectedRow();
        if (i != -1) {
            int j = JOptionPane.showConfirmDialog(null, "Bạn Có Chắc Chắn Muốn Loại Bỏ Sản Phẩm Này", "Thông Báo", JOptionPane.YES_NO_OPTION);
            if (j == JOptionPane.YES_OPTION) {
                qlSanPham.xoaSanPham(i);
            }
        }
        reset();
    }//GEN-LAST:event_btXoaSanPhamActionPerformed

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        int i = tableSanPham.getSelectedRow();
        int sz= ds_SanPham.size();
        if (i < sz && i != -1) {
            //SAch
            tfMaSanPham.setText(ds_SanPham.get(i).getMaSanPham());
            tfTenSanPham.setText(ds_SanPham.get(i).getTenSanPham());
            tfLoaiSanPham.setText(ds_SanPham.get(i).getLoaiSanPham());
            tfThuongHieu.setText(ds_SanPham.get(i).getThuongHieu());
            tfDonVi.setText(ds_SanPham.get(i).getDonVi());
            tfSoLuong.setText(ds_SanPham.get(i).getSoLuong() + "");
            tfGiaMua.setText(ds_SanPham.get(i).getGiaMua() + "");
            tfGiaBan.setText(ds_SanPham.get(i).getGiaBan() + "");
        } 
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int i = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thoát", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            qlSanPham.writeSanPhamToFile();
            qlNhanVien.writeNhanVienToFile();
            //qlBanHang.writeHoaDonToFile();
//            qlThuChi.writeThuChiToFile();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnXacNhan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhan7ActionPerformed
        ArrayList<SanPham> listSanPhamTrongHoaDon = getListSPTrongHD();
        long tongTien = 0;
        String tenKhachHang=tenKhachHangField.getText().trim();
        String soDienThoai=soDienThoaiField.getText();      
        if(tenKhachHang.length()==0 && tenKhachHang.length()==0) 
        {
            tenKhachHang = "Khachle";
            soDienThoai = "x";
        }
        for (int i = 0; i < listSanPhamTrongHoaDon.size(); i++) {
            SanPham sp = listSanPhamTrongHoaDon.get(i);
            tongTien += sp.getGiaBan() * sp.getSoLuong();
        }
        if (!listSanPhamTrongHoaDon.isEmpty()) {
            String maHoaDon = setMaHoaDon();
            String ngay = getCurrentDate();
            try {
                qlBanHang.taoHoaDon(new HoaDon(maHoaDon,tenKhachHang,soDienThoai, ngay, listSanPhamTrongHoaDon, tongTien));
                inHoaDon(listSanPhamTrongHoaDon, tongTien);
            } catch (IOException ex) {
                Logger.getLogger(FrameNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(FrameNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        listSanPhamTrongHoaDon.clear();
        tfTongTien.setText("");
        DefaultTableModel model = (DefaultTableModel) tableBanHang.getModel();
        model.setRowCount(0);
        tenKhachHangField.setText("");
        tfThemSoLuong.setText("");
        tenKhachHangField.setText("");
        soDienThoaiField.setText("");
    }//GEN-LAST:event_btnXacNhan7ActionPerformed

    private void DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatActionPerformed
        // TODO add your handling code here:
        qlSanPham.writeSanPhamToFile();
        qlNhanVien.writeNhanVienToFile();
        //qlBanHang.writeHoaDonToFile();
//        qlThuChi.writeThuChiToFile();
        qlDangNhap.logout();
        this.setVisible(false);
    }//GEN-LAST:event_DangXuatActionPerformed

    private void btThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemVaoGioHangActionPerformed
         String thongBao = "";
        if (tfThemMaSanPham.getText().trim().length() == 0) {
            thongBao += "Chưa Điền mã sản phẩm";
        }
        if (tfThemSoLuong.getText().trim().length() == 0 || tfThemSoLuong.getText().trim().equals("0")) {
            thongBao += "\nChưa Điền số lượng";
        }
        if (thongBao.length() != 0) {
            JOptionPane.showMessageDialog(null, thongBao, "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            SanPham sp;
            int giaBan = 0;
            String tenSanPham = null;
            String maSanPham = tfThemMaSanPham.getText().trim();
            String donVi = null;
            String loaiSanPham=null;
            int soLuong = Integer.parseInt(tfThemSoLuong.getText().trim());
            int checkSoLuong = -1;
                    for (int i = 0; i < ds_SanPham.size(); i++) {
                        if (maSanPham.equalsIgnoreCase(ds_SanPham.get(i).getMaSanPham())) {
                            maSanPham = ds_SanPham.get(i).getMaSanPham();
                            giaBan = ds_SanPham.get(i).getGiaBan();
                            tenSanPham = ds_SanPham.get(i).getTenSanPham();
                            checkSoLuong= ds_SanPham.get(i).getSoLuong() - soLuong;
                            loaiSanPham = ds_SanPham.get(i).getLoaiSanPham();
                            int giaMua = ds_SanPham.get(i).getGiaMua();
                            String thuongHieu = ds_SanPham.get(i).getThuongHieu();
                            donVi = ds_SanPham.get(i).getDonVi();
                            int index = i;
                            SanPham s = new SanPham(maSanPham, tenSanPham,loaiSanPham,giaMua, giaBan, thuongHieu,donVi,checkSoLuong);
                            if (checkSoLuong > 0) {
                                qlSanPham.suaThongTin(s, index);
                            }                             
                            else if (checkSoLuong == 0) {
                                qlSanPham.xoaSanPham(index);
                            } 
                            else {
                                JOptionPane.showMessageDialog(null, "Không Đủ Hàng", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                            }
                            break;
                        }
                    }
            if (checkSoLuong >= 0) {
                boolean checkTrungMaSP = false;
                sp = new SanPham(maSanPham, tenSanPham,loaiSanPham,donVi, soLuong, giaBan);
                DefaultTableModel model = (DefaultTableModel) tableBanHang.getModel();
                for (int i = 0;i<tableBanHang.getRowCount();i++){
                    if (sp.getMaSanPham().equalsIgnoreCase(tableBanHang.getValueAt(i, 0).toString())) {
                        int sl = Integer.parseInt(tableBanHang.getValueAt(i, 4).toString()) + soLuong;
                        tableBanHang.setValueAt(sl+"", i, 4);
                        tableBanHang.setValueAt(sl*sp.getGiaBan()+"", i, 6);
                        checkTrungMaSP = true;
                        break;
                    }
                }
                if (!checkTrungMaSP){
                    model.addRow(new Object[]{
                        sp.getMaSanPham(),
                        sp.getTenSanPham(),
                        sp.getLoaiSanPham(),
                        sp.getDonVi(),
                        sp.getSoLuong(),
                        sp.getGiaBan(),
                        sp.getGiaBan() * sp.getSoLuong()
                    });
                }
                int tongTien =0;
                for ( int i=0 ; i<tableBanHang.getRowCount() ; i++){
                    tongTien+=Integer.parseInt(tableBanHang.getValueAt(i,6).toString());
                }
                if(tongTien==0) tfTongTien.setText("");
                else {
                    tfTongTien.setText(tongTien+"");
                }   
            } 
            else {
                JOptionPane.showMessageDialog(null, "Sai Mã Hàng", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        tfThemMaSanPham.setText("");
        tfThemSoLuong.setText("");
    }//GEN-LAST:event_btThemVaoGioHangActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thoát", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
//            qlSanPham.update();
            qlSanPham.writeSanPhamToFile();
            qlNhanVien.writeNhanVienToFile();
            //qlBanHang.writeHoaDonToFile();
//            qlThuChi.writeThuChiToFile();
            System.exit(0);
        }
    }//GEN-LAST:event_ThoatActionPerformed

    private void tfTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenSanPhamActionPerformed

    private void tfMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaSanPhamActionPerformed

    private void tenKhachHangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenKhachHangFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenKhachHangFieldActionPerformed

    private void tfThemSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThemSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThemSoLuongActionPerformed

    private void tfTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTongTienActionPerformed

    private void tfLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoaiSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoaiSanPhamActionPerformed

    private void btXoakhoigiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoakhoigiohangActionPerformed
        DefaultTableModel Model1 =(DefaultTableModel) tableBanHang.getModel();
        DefaultTableModel Model2 =(DefaultTableModel) tableSanPham.getModel();
        int selected = tableBanHang.getSelectedRow();
        System.out.print(selected);
        if(selected!=-1)
        {
            SanPham sp;
            int giaBan = 0;
            String tenSanPham = null;
            String maSanPhamRmvd = tableBanHang.getValueAt(selected,0).toString();
            String donVi = null;
            String loaiSanPham=null;
            int soLuongMua =0;
            int giaMua=0;
            System.out.println(soLuongMua);
            String thuongHieu=null;
            for (int i=0 ; i< tableSanPham.getRowCount(); i++) {
                if(maSanPhamRmvd.equalsIgnoreCase(tableSanPham.getValueAt(i,1).toString())) {
                    soLuongMua += Integer.parseInt( tableSanPham.getValueAt(i, 7).toString());
                    soLuongMua += Integer.parseInt(tableBanHang.getValueAt(selected, 4).toString());
                    System.out.println(soLuongMua);
                            giaBan = ds_SanPham.get(i).getGiaBan();
                            tenSanPham = ds_SanPham.get(i).getTenSanPham();
                            loaiSanPham = ds_SanPham.get(i).getLoaiSanPham();
                            giaMua = ds_SanPham.get(i).getGiaMua();
                            thuongHieu = ds_SanPham.get(i).getThuongHieu();
                            donVi = ds_SanPham.get(i).getDonVi();
                            sp = new SanPham(maSanPhamRmvd,tenSanPham,loaiSanPham,giaMua,giaBan,thuongHieu,donVi,soLuongMua);
                            qlSanPham.suaThongTin(sp, i);
                    break;
                }
            }          
            Model1.removeRow(tableBanHang.getSelectedRow());
            
            int tongTien =0;
                for ( int i=0 ; i<tableBanHang.getRowCount() ; i++){
                    tongTien+=Integer.parseInt(tableBanHang.getValueAt(i,6).toString());
                }
                if(tongTien==0) tfTongTien.setText("");
                else {
                    tfTongTien.setText(tongTien+"");
                }    
        }
        else 
        {
            if(tableBanHang.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Giỏ Hàng trống.!");
            }
            else 
            {
                JOptionPane.showMessageDialog(this,"Chọn 1 sản phẩm mà bạn muốn đưa ra khỏi giỏ hàng.!");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btXoakhoigiohangActionPerformed

    private void soDienThoaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soDienThoaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soDienThoaiFieldActionPerformed

    private void tfThemMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThemMaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThemMaSanPhamActionPerformed

    private void reset() {
        tfMaSanPham.setEditable(false);
        tfMaSanPham.setText("");
        tfTenSanPham.setEditable(false);
        tfTenSanPham.setText("");
        tfThuongHieu.setEditable(false);
        tfThuongHieu.setText("");
        tfLoaiSanPham.setEditable(false);
        tfLoaiSanPham.setText("");
        tfDonVi.setEditable(false);
        tfDonVi.setText("");
        tfGiaBan.setEditable(false);
        tfGiaBan.setText("");
        tfGiaMua.setEditable(false);
        tfGiaMua.setText("");
        tfSoLuong.setEditable(false);
        tfSoLuong.setText("");
    }

    public String getDate(JLabel label) {
        Calendar date = new GregorianCalendar();
        String dateShow = String.valueOf(date.get(Calendar.DATE)) + " Tháng " + String.valueOf(date.get(Calendar.MONTH) + 1) + " Năm " + String.valueOf(date.get(Calendar.YEAR));
        switch (date.get(Calendar.DAY_OF_WEEK)) {
            case 1:
                dateShow = "Chủ Nhật Ngày " + dateShow;
                break;
            case 2:
                dateShow = "Thứ Hai Ngày " + dateShow;
                break;
            case 3:
                dateShow = "Thứ Ba Ngày " + dateShow;
                break;
            case 4:
                dateShow = "Thứ Tư Ngày " + dateShow;
                break;
            case 5:
                dateShow = "Thứ Năm Ngày " + dateShow;
                break;
            case 6:
                dateShow = "Thứ Sáu Ngày " + dateShow;
                break;
            case 7:
                dateShow = "Thứ Bảy Ngày " + dateShow;
                break;
            default:
                break;
        }
        return dateShow;
    }

    private ArrayList<SanPham> getListSPTrongHD() {
        ArrayList<SanPham> listSP = new ArrayList<>();
        int cs = tableBanHang.getColumnCount();
        int rs = tableBanHang.getRowCount();
        for (int i = 0; i < rs; i++) {
            String maSP = tableBanHang.getValueAt(i, 0).toString();
            String tenSP = tableBanHang.getValueAt(i, 1).toString();
            String loaiSP = tableBanHang.getValueAt(i,2).toString();
            String donVi = tableBanHang.getValueAt(i, 3).toString();
            int soLuong = Integer.parseInt(tableBanHang.getValueAt(i, 4).toString());
            int donGia = Integer.parseInt(tableBanHang.getValueAt(i, 5).toString());
            SanPham sp = new SanPham(maSP, tenSP,loaiSP, donVi, soLuong,donGia );
            listSP.add(sp);
        }
        return listSP;
    }

    private String setMaHoaDon() {
        int i = ds_HoaDon.size() + 1;
        return "HD" + i;
    }

    private void inHoaDon(ArrayList<SanPham> listSPTrongHoaDon, long tongTien) throws FileNotFoundException, DocumentException, IOException {
        Calendar date = new GregorianCalendar();
        File file = new File("HoaDon.pdf");
        Document document = new Document(PageSize.A4);
        BaseFont bf1 = BaseFont.createFont("vuArial.ttf", BaseFont.IDENTITY_H, true);
        FileOutputStream outFile = new FileOutputStream(file);
        PdfWriter.getInstance(document, outFile);
        document.open();
        com.itextpdf.text.Font fontTenCuaHang = new com.itextpdf.text.Font(bf1, 18, com.itextpdf.text.Font.BOLD, BaseColor.BLUE);
        //com.itextpdf.text.Font fontTieuDe = new com.itextpdf.text.Font(bf1, 14, com.itextpdf.text.Font.NORMAL, BaseColor.BLACK);
        //com.itextpdf.text.Font fontMuc = new com.itextpdf.text.Font(bf1, 14, com.itextpdf.text.Font.BOLD, BaseColor.BLACK);
        com.itextpdf.text.Font fontChung = new com.itextpdf.text.Font(bf1, 13, com.itextpdf.text.Font.NORMAL, BaseColor.BLACK);
        com.itextpdf.text.Font fontten = new com.itextpdf.text.Font(bf1, 13, com.itextpdf.text.Font.NORMAL, BaseColor.RED);
        com.itextpdf.text.Font fontChungDam = new com.itextpdf.text.Font(bf1, 13, com.itextpdf.text.Font.BOLD, BaseColor.BLACK);
        //com.itextpdf.text.Font fontChuKy = new com.itextpdf.text.Font(bf1, 16, com.itextpdf.text.Font.BOLD, BaseColor.BLACK);
        //com.itextpdf.text.Font fontLienLac = new com.itextpdf.text.Font(bf1, 7, com.itextpdf.text.Font.UNDEFINED, BaseColor.BLACK);
        //document.add(new Paragraph("CỬA HÀNG MEDIA ONE", fontTenCuaHang));
        Paragraph ph1 = new Paragraph("HÓA ĐƠN BÁN HÀNG", fontTenCuaHang);
        ph1.setAlignment(Element.ALIGN_CENTER);
        document.add(ph1);
        Paragraph ph2 = new Paragraph(" Ngày " + date.get(Calendar.DATE) + " Tháng " + (date.get(Calendar.MONTH) + 1) + " Năm " + date.get(Calendar.YEAR) + " " + date.get(Calendar.HOUR)+ ":"+date.get(Calendar.SECOND), fontChung );
//        Paragraph ph2 = new Paragraph("Liên 2: Giao cho người mua", fontChung);
        ph2.setAlignment(Element.ALIGN_CENTER);
        document.add(ph2);
        Paragraph ph3 = new Paragraph("Điện Thoại : (04)8888.8888", fontChung);
        ph3.setAlignment(Element.ALIGN_CENTER);
        document.add(ph3);
        document.add(new Paragraph(" ", fontChung));
        document.add(new Paragraph("CỬA HÀNG TẠP HÓA", fontten));
        document.add(new Paragraph("Địa Chỉ: Số 96 Đường Giải Phóng Hai Bà Trưng Hà Nội", fontChung));
//        document.add(new Paragraph("Điện Thoại : (04)8888.8888", fontChung));
//        document.add(new Paragraph("Số Tài Khoản: 021111111111", fontChung));
//        document.add(new Paragraph("Tại: NH Thương Mại CP Ngoại Thương Việt Nam Chi nhánh Hà Nội", fontChung));
        document.add(new Paragraph("Nhân Viên Bán Hàng: " + nv.getTenNhanVien(), fontChungDam));
        document.add(new Paragraph("          ", fontChung));
        document.add(getTable(listSPTrongHoaDon));
        document.add(new Paragraph("Tổng Số Tiền Cần Thanh Toán: " + tongTien + " VNĐ", fontChung));
        document.add(new Paragraph("          ", fontChung));
//        document.add(new Paragraph(" nv004         Người mua hàng                                                              Người viết hóa đơn", fontChung));
//        document.add(new Paragraph(" (Ký, ghi rõ họ tên)", fontChung));
//        document.add(new Paragraph("   ", fontChung));
//        document.add(new Paragraph("                                                                                         " +nv.getTenNhanVien(), fontChungDam));
        document.close();
        Desktop.getDesktop().open(file);
        //File file1 = new File(file.getPath() + ".xls");
    }

    private PdfPTable getTable(ArrayList<SanPham> listSPTrongHoaDon) throws DocumentException, IOException {
        BaseFont bf1 = BaseFont.createFont("vuArial.ttf", BaseFont.IDENTITY_H, true);
        com.itextpdf.text.Font fontChung = new com.itextpdf.text.Font(bf1, 14, com.itextpdf.text.Font.NORMAL, BaseColor.BLACK);
        PdfPTable table = new PdfPTable(8);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{25f, 50f, 60f, 50f, 30f, 40f,60f,70f});
        table.addCell(new PdfPCell(new Paragraph("STT", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Mã Sản Phẩm", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Tên Sản Phẩm", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Loại Sản Phẩm", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Đơn Vị", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Số Lượng", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Đơn Giá (VNĐ)", fontChung)));
        table.addCell(new PdfPCell(new Paragraph("Thành Tiền", fontChung)));
        for (int i = 0; i < listSPTrongHoaDon.size(); i++) {
            SanPham sp = listSPTrongHoaDon.get(i);
            table.addCell(new PdfPCell(new Paragraph(i + 1 + "", fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getMaSanPham(), fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getTenSanPham(), fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getLoaiSanPham(), fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getDonVi(), fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getSoLuong() + "", fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getGiaBan() + "", fontChung)));
            table.addCell(new PdfPCell(new Paragraph(sp.getGiaBan() * sp.getSoLuong() + "", fontChung)));
        }
        return table;
    }

    private String getCurrentDate() {
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date dates = new Date();
        return dateFormat.format(dates);
    }

    private String getCureentTime() {
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        Date dates = new Date();
        return dateFormat.format(dates);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DangXuat;
    private javax.swing.JMenuItem Thoat;
    private javax.swing.JButton btCapNhatSanPham;
    private javax.swing.JButton btThemSanPham;
    private javax.swing.JButton btThemVaoGioHang;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btXoaSanPham;
    private javax.swing.JButton btXoakhoigiohang;
    private javax.swing.JButton btnXacNhan7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbNgayThangNam;
    private javax.swing.JLabel lbchao;
    private javax.swing.JLabel lblDonVi;
    private javax.swing.JLabel lblGiaBan2;
    private javax.swing.JLabel lblGiaMua2;
    private javax.swing.JLabel lblLoaiSanPham;
    private javax.swing.JLabel lblMaSanPham2;
    private javax.swing.JLabel lblNhaCungCap2;
    private javax.swing.JLabel lblTenSanPham2;
    private javax.swing.JLabel lbthem3;
    private javax.swing.JPanel pnChiTietBanHang7;
    private javax.swing.JPanel pnKhachHang6;
    private javax.swing.JPanel pnThongTinSPBanHang;
    private javax.swing.JTextField soDienThoaiField;
    private javax.swing.JTable tableBanHang;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField tenKhachHangField;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfGiaBan;
    private javax.swing.JTextField tfGiaMua;
    private javax.swing.JTextField tfLoaiSanPham;
    private javax.swing.JTextField tfMaSanPham;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenSanPham;
    private javax.swing.JTextField tfThemMaSanPham;
    private javax.swing.JTextField tfThemSoLuong;
    private javax.swing.JTextField tfThuongHieu;
    private javax.swing.JTextField tfTongTien;
    // End of variables declaration//GEN-END:variables

}
