/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import FileDB.FileDB;
import com.sun.glass.events.KeyEvent;
import controller.QuanLySanPham;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import model.SanPham;

/**
 *
 * @author Administrator
 */
public class FrameChiTietSanPham extends javax.swing.JFrame {

    /**
     * Creates new form FrameChiTietSanPham
     */
    int type;
    int index;
    QuanLySanPham qlsp;

    public FrameChiTietSanPham() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public FrameChiTietSanPham(QuanLySanPham qlsp, int index, int type) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.type = type;
        this.index = index;
        this.qlsp = qlsp;
        if (this.type == 1) { 
            setTitle("CẬP NHẬT THÔNG TIN SẢN PHẨM");
            lbTitel.setText("Cập Nhật");
            this.setTitle("CẬP NHẬT THÔNG TIN SẢN PHẨM");
            tfTenSanPham.setText(qlsp.getDS_SanPham().get(index).getTenSanPham());
            tfMaSanPham.setText(qlsp.getDS_SanPham().get(index).getMaSanPham());
            tfLoaiSanPham.setText(qlsp.getDS_SanPham().get(index).getLoaiSanPham());
            tfThuongHieu.setText(qlsp.getDS_SanPham().get(index).getThuongHieu());
            tfDonVi.setText(qlsp.getDS_SanPham().get(index).getDonVi());
            tfSoLuong.setText(qlsp.getDS_SanPham().get(index).getSoLuong() + "");
            tfGiaMua.setText(qlsp.getDS_SanPham().get(index).getGiaMua() + "");
            tfGiaBan.setText(qlsp.getDS_SanPham().get(index).getGiaBan() + "");
        } 
        else if ( this.type==0) {
            setTitle("THÊM SẢN PHẨM");
            lbTitel.setText("Thêm Sản Phẩm");
            this.setTitle("Thêm Sản Phẩm");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitel = new javax.swing.JLabel();
        lblMaSanPham2 = new javax.swing.JLabel();
        lblTenSanPham2 = new javax.swing.JLabel();
        lblNhaCungCap2 = new javax.swing.JLabel();
        lblLoaiSanPham2 = new javax.swing.JLabel();
        lblGiaBan2 = new javax.swing.JLabel();
        btThemSanPham = new javax.swing.JButton();
        tfMaSanPham = new javax.swing.JTextField();
        tfTenSanPham = new javax.swing.JTextField();
        tfThuongHieu = new javax.swing.JTextField();
        lblGiaMua3 = new javax.swing.JLabel();
        tfGiaMua = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        tfGiaBan = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        btHuy = new javax.swing.JButton();
        lblNhaCungCap3 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        lblNhaCungCap4 = new javax.swing.JLabel();
        tfDonVi = new javax.swing.JTextField();
        tfLoaiSanPham = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbTitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMaSanPham2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaSanPham2.setText("Mã Sản Phẩm:");

        lblTenSanPham2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenSanPham2.setText("Tên Sản Phẩm:");

        lblNhaCungCap2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhaCungCap2.setText("Thương Hiệu");

        lblLoaiSanPham2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoaiSanPham2.setText("Loại Sản Phẩm:");

        lblGiaBan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGiaBan2.setText("Giá Bán:");

        btThemSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ok.png"))); // NOI18N
        btThemSanPham.setText("OK");
        btThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemSanPhamActionPerformed(evt);
            }
        });

        lblGiaMua3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGiaMua3.setText("Giá Mua:");

        tfGiaMua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGiaMuaKeyTyped(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 204, 0));
        jLabel46.setText("VND");

        tfGiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGiaBanKeyTyped(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 204, 0));
        jLabel47.setText("VND");

        btHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove-button.png"))); // NOI18N
        btHuy.setText("Hủy");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        lblNhaCungCap3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhaCungCap3.setText("Số Lượng:");

        tfSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSoLuongKeyTyped(evt);
            }
        });

        lblNhaCungCap4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhaCungCap4.setText("Đơn Vị");

        tfDonVi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDonViKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(btThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                            .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGiaMua3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNhaCungCap3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTenSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLoaiSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGiaBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNhaCungCap2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNhaCungCap4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfTenSanPham)
                                .addComponent(tfMaSanPham)
                                .addComponent(tfThuongHieu)
                                .addComponent(tfSoLuong)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfGiaMua, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfGiaBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(tfDonVi)
                                .addComponent(tfLoaiSanPham))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblGiaBan2, lblGiaMua3, lblLoaiSanPham2, lblMaSanPham2, lblNhaCungCap2, lblNhaCungCap3, lblTenSanPham2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btHuy, btThemSanPham});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbTitel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiSanPham2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(tfLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhaCungCap2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhaCungCap4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhaCungCap3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiaMua3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHuy))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblGiaBan2, lblGiaMua3, lblLoaiSanPham2, lblMaSanPham2, lblNhaCungCap2, lblNhaCungCap3, lblTenSanPham2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel46, jLabel47, tfGiaBan, tfGiaMua, tfMaSanPham, tfSoLuong, tfTenSanPham, tfThuongHieu});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btHuy, btThemSanPham});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btHuyActionPerformed

    private void btThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemSanPhamActionPerformed
        String thongBao = "";
        if (tfMaSanPham.getText().trim().length() == 0) {
            thongBao += "Chưa Điền mã sản phẩm";
        }
        if (tfTenSanPham.getText().trim().length() == 0) {
            thongBao += "\nChưa Điền tên sản phẩm";
        }
        if (tfLoaiSanPham.getText().trim().length() == 0) {
            thongBao += "\nChưa Điền loại sản phẩm";
        }
        if (tfThuongHieu.getText().trim().length() == 0) {
            thongBao += "\nChưa điền thương hiệu của sản phẩm";
        }
        if (tfDonVi.getText().trim().length() == 0) {
            thongBao += "\nChưa Điền đơn vị sản phẩm";
        }
        if (tfGiaMua.getText().trim().length() == 0) {
            thongBao += "\nChưa điền giá mua";
        }
        if (tfGiaBan.getText().trim().length() == 0) {
            thongBao += "\nChưa điền giá Bán";
        }
        if (tfSoLuong.getText().trim().length() == 0) {
            thongBao += "\nChưa điền số lượng";
        }
        if (thongBao.length() != 0) {
            JOptionPane.showMessageDialog(null, thongBao, "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String maSanPham = tfMaSanPham.getText();
            String tenSanPham = tfTenSanPham.getText();
            String loaiSanPham = tfLoaiSanPham.getText(); 
            String thuongHieu = tfThuongHieu.getText();
            String donVi = tfDonVi.getText();
            int giaMua = Integer.parseInt(tfGiaMua.getText());
            int giaBan = Integer.parseInt(tfGiaBan.getText());
            int soLuong = Integer.parseInt(tfSoLuong.getText());

            switch (this.type) {
                case 0: //Them SP
                    SanPham sp = new SanPham(maSanPham, tenSanPham,loaiSanPham, giaMua, giaBan, thuongHieu,donVi, soLuong);
                    qlsp.themSanPham(sp);
                    break;
                case 1: //Capnhatsp
                    SanPham s = new SanPham(maSanPham, tenSanPham,loaiSanPham, giaMua, giaBan, thuongHieu,donVi, soLuong);
                    qlsp.suaThongTin(s, index);
                    break;
            }
            this.dispose();
        }
    }//GEN-LAST:event_btThemSanPhamActionPerformed

    private void tfSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSoLuongKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() > KeyEvent.VK_9 || evt.getKeyChar() < KeyEvent.VK_0) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tfSoLuongKeyTyped

    private void tfGiaMuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGiaMuaKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() > KeyEvent.VK_9 || evt.getKeyChar() < KeyEvent.VK_0) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tfGiaMuaKeyTyped

    private void tfGiaBanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGiaBanKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() > KeyEvent.VK_9 || evt.getKeyChar() < KeyEvent.VK_0) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tfGiaBanKeyTyped

    private void tfDonViKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDonViKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDonViKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btThemSanPham;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTitel;
    private javax.swing.JLabel lblGiaBan2;
    private javax.swing.JLabel lblGiaMua3;
    private javax.swing.JLabel lblLoaiSanPham2;
    private javax.swing.JLabel lblMaSanPham2;
    private javax.swing.JLabel lblNhaCungCap2;
    private javax.swing.JLabel lblNhaCungCap3;
    private javax.swing.JLabel lblNhaCungCap4;
    private javax.swing.JLabel lblTenSanPham2;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfGiaBan;
    private javax.swing.JTextField tfGiaMua;
    private javax.swing.JTextField tfLoaiSanPham;
    private javax.swing.JTextField tfMaSanPham;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenSanPham;
    private javax.swing.JTextField tfThuongHieu;
    // End of variables declaration//GEN-END:variables
}
